[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["cd packages/web && bun run build:prod"]

[start]
cmd = "cd packages/web && bun run server.ts"
